version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=3
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
  kafka-1:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9091:9091"
    volumes:
      - "kafka_data:/bitnami_1"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka-1:9091,kafka-2:9092,kafka-3:9093
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper

  kafka-2:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami_2"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka-1:9091,kafka-2:9092,kafka-3:9093
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper

  kafka-3:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami_3"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=kafka-1:9091,kafka-2:9092,kafka-3:9093
      - ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper

  connect:
    build:
      context: ./container/connect
      dockerfile: Dockerfile
    container_name: connect
    hostname: connect
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - BOOTSTRAP_SERVERS=kafka-1:9091,kafka-2:9092,kafka-3:9093
    links:
      - zookeeper:zookeeper
      - kafka-1:kafka-1
      - kafka-2:kafka-2
      - kafka-3:kafka-3
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3

  postgres_custom:
    build:
      context: .
      dockerfile: ./container/postgres/Dockerfile
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0
    restart: "no"
    ports:
      - "9050:9050"
    environment:
      SERVER_PORT: 9050
      KAFKA_BROKERCONNECT: "kafka-1:9091,kafka-2:9092,kafka-3:9093"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka-1"
      - "kafka-2"
      - "kafka-3"
  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "sleep 10 &&  /usr/bin/mc config host add myminio http://minio:9000 minio minio123; sleep 10; /usr/bin/mc mb myminio/commerce;  /usr/bin/mc policy download myminio/commerce;  exit 0;  "

  datagen:
    build:
      context: .
      dockerfile: ./container/datagen/Dockerfile
    entrypoint:
      - python
      - ./gen_user_payment_data.py
    container_name: datagen
    restart: on-failure
    depends_on:
      - postgres_custom
  job:
    build:
      context: .
      dockerfile: ./container/job/Dockerfile
    entrypoint:
      - python
      - ./main/main.py
    container_name: job
    restart: on-failure
    depends_on:
      - postgres_custom
  debezium-ui:
    image: quay.io/debezium/debezium-ui:2.0
    container_name: debezium-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
    driver: local
