version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  connect:
    build:
      context: ./container/connect
      dockerfile: Dockerfile
    container_name: connect
    hostname: connect
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - BOOTSTRAP_SERVERS=kafka:9092
    links:
      - zookeeper:zookeeper
      - kafka:kafka
    depends_on:
      - zookeeper
      - kafka

  postgres_custom:
    build:
      context: .
      dockerfile: ./container/postgres/Dockerfile
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "sleep 10 &&  /usr/bin/mc config host add myminio http://minio:9000 minio minio123; sleep 10; /usr/bin/mc mb myminio/commerce;  /usr/bin/mc policy download myminio/commerce;  exit 0;  "

  datagen:
    build:
      context: .
      dockerfile: ./container/datagen/Dockerfile
    entrypoint:
      - python
      - ./gen_user_payment_data.py
    container_name: datagen
    restart: on-failure
    depends_on:
      - postgres_custom
  job:
    build:
      context: .
      dockerfile: ./container/job/Dockerfile
    entrypoint:
      - python
      - ./main/main.py
    container_name: job
    restart: on-failure
    depends_on:
      - postgres_custom
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    restart: "no"
    ports:
      - "9999:9999"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      # JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  debezium-ui:
    image: quay.io/debezium/debezium-ui:2.0
    container_name: debezium-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
    tty: true
    stdin_open: true
    restart: unless-stopped
    # add elastic search
  target_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    restart: on-failure
    ports:
      - 5601:5601
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_HOSTS=http://target_db:9200
    depends_on:
      - target_db
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
    driver: local
